### ISSUE TITLE
Consider publishing ARM bdist wheels for MacOS

### ISSUE THREAD

**Issue by zachmullen** [InsightSoftwareConsortium/ITKThickness3D#44]
Hi all,

I'm using this great library, but unfortunately can't pip install it on my newer macbook because only x86_64 wheels are currently published. Would you consider publishing ARM wheels for MacOS also, for python 3.8+?

Thanks!

**Comment by nnpk** [comment]
Same request here. This would be very helpful. Thanks!

**Comment by panlilio** [comment]
I have the same issue with my new macbook. ARM wheels would be very much appreciated.

**Comment by T4mmi** [comment]
Hi, I don't have access to an ARM-powered machine so won't be able to help there ... but:   
Releases deployment are processed through CI, based on https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/blob/main/.github/workflows/build-test-cxx.yml that appears to handle macOS ... so theoretically you should be able to mimic the pipeline in order to compile it locally (not sure that ITK has a Mac ARM-based CI runner, maybe this could be the issue)

**Comment by thewtex** [comment]
Now available with the update to ITK 5.4.0:

  https://pypi.org/project/itk-thickness3d/#files

**Comment by zachmullen** [comment]
Awesome! thank you @thewtex !
